= Spring Boot Application with RabbitMQ, JBPM (Kie & Custom APIs) Integration

== Pre-Reqs

* Installed RabbitMQ Server
** Create RabbitMQ Cluster in OCP
*** rabbitmq installation - https://github.com/redhat-cop/containers-quickstarts/tree/master/rabbitmq[redhat-cop/containers-quickstarts/rabbitmq] :				
*** Configure RabbitMQ https://www.rabbitmq.com/plugins.html#ways-to-enable-plugins[Plugin config for AMQP]
*** test rabbitmq - https://github.com/cristianprofile/spring-boot-rabbitmq-integration-test[Spring boot Rabbitmq with integration test]
*** access from local the ocp rabbitmq installation eg. https://blog.openshift.com/openshift-connecting-database-using-port-forwarding/[Connecting to a Database Using Port Forwarding in OpenShift]
	
* Installed Database
** h2 (no installation see application-h2.properties)
** mysql local (installaton required and config see application-mysql.properties and pm.xml)
** remote database custom (eg. https://blog.openshift.com/openshift-connecting-database-using-port-forwarding/[Connecting to a Database Using Port Forwarding in OpenShift])
	
* KJAR
** we use [URL TBD]payments KJAR
** Build it as follows
	
	mvn clean deploy -s /home/stkousso/.m2/hapoalim-settings.xml


=== h2 local profile

export SPRING_RABBITMQ_HOST=127.0.0.1 
export SPRING_RABBITMQ_PORT=5672 
export SPRING_RABBITMQ_USERNAME=pamservice 
export SPRING_RABBITMQ_PASSWORD=pamservice

oc port-forward rabbitmq-0 9672:5672


* pam-rabbitmt-service.xml: defines KJAR to upload (since we use *LocalContainersStartupStrategy* we use kie.module.gav=${SB_KIE_MODULE_GAV:com.redhat:payments:4.7.0}
* Build and Run (locally Spring-Boot app with h2, rabbitmq port-forward to port 5672 required, pam-rabbitmq-service.xml configuration with com.redhat:payments:VERSION)

	mvn clean package spring-boot:run -Dspring.profiles.active=h2 -Dorg.kie.server.startup.strategy=LocalContainersStartupStrategy -Dorg.kie.server.mode=DEVELOPMENT -DSB_KIE_MODULE_GAV=com.redhat:payments:4.11.0


* SWAGGER Available 
** /pam APIs
	http://127.0.0.1:8090/rest/swagger.json 
** KIE Server APIs
	http://127.0.0.1:8090/rest/api-docs?url=http://localhost:8090/rest/swagger.json	

* Connection to (BC) Controller 
** kieserver.controllers=ws://127.0.0.1:8080/business-central/websocket/controller
** username/password (look at pam-rabbitmq-service.xml and has to match BC user logged in)
* TEST
	curl -u 'demo:demo' -H "accept: application/json" -H "content-type: application/json" -X POST http://127.0.0.1:8090/rest/pam/process/message/start/chequestransactions/15
	curl -u 'demo:demo' -H "accept: application/json" -H "content-type: application/json" -X POST http://127.0.0.1:8090/rest/pam/process/message/continue/15/CHEQUES_CREATED
	curl -u 'demo:demo' -H "accept: application/json" -H "content-type: application/json" -X POST http://127.0.0.1:8090/rest/pam/process/message/continue/15/CHEQUES_SCANNED


=== mysql local profile

* RabbitMQ Configurations exported as ENV Variables (or added to link:./src/main/resources/application-mysql.properties[application-mysql.properties] and for Quartz enabled link:./src/main/resources/application-mysql.properties[application-mysql.properties])

	export SPRING_RABBITMQ_HOST=127.0.0.1 
	export SPRING_RABBITMQ_PORT=5672 
	export SPRING_RABBITMQ_USERNAME=pamservice 
	export SPRING_RABBITMQ_PASSWORD=pamservice

* Port-forwarding to the Openshift Cluster (note could be docker image)

	oc port-forward rabbitmq-0 9672:5672

* Testing once started see 

* Getting content of DB running/history instances (also look at link:.RHPAM-API-REQUESTS.txt[RHPAM-API-REQUESTS.txt] 

mysql>  select id,correlationKey,externalId,processId,processInstanceId,processVersion,slaCompliance,sla_due_date,start_date,status from ProcessInstanceLog;
+----+----------------+----------------------------+---------------------+-------------------+----------------+---------------+---------------------+---------------------+--------+
| id | correlationKey | externalId                 | processId           | processInstanceId | processVersion | slaCompliance | sla_due_date        | start_date          | status |
+----+----------------+----------------------------+---------------------+-------------------+----------------+---------------+---------------------+---------------------+--------+
|  1 | 1              | com.redhat:payments:4.11.0 | chequestransactions |                 1 | 2.0            |             3 | 2020-03-04 14:29:25 | 2020-03-04 14:26:25 |      1 |
|  2 | 2              | com.redhat:payments:4.11.0 | chequestransactions |                 2 | 2.0            |             3 | 2020-03-05 09:26:24 | 2020-03-05 09:23:24 |      1 |
|  3 | 3              | com.redhat:payments:4.11.0 | my-process          |                54 | 1.0            |             0 | NULL                | 2020-03-05 19:28:48 |      2 |
|  4 | 5              | com.redhat:payments:4.11.0 | my-process          |                55 | 1.0            |             0 | NULL                | 2020-03-05 19:44:51 |      2 |
|  5 | 5              | com.redhat:payments:4.11.0 | my-process          |                56 | 1.0            |             0 | NULL                | 2020-03-05 19:49:59 |      2 |
|  6 | 101            | com.redhat:payments:4.11.0 | my-process          |                57 | 1.0            |             0 | NULL                | 2020-03-05 20:25:14 |      2 |
|  7 | 102            | com.redhat:payments:4.11.0 | my-process          |                58 | 1.0            |             0 | NULL                | 2020-03-05 20:33:53 |      2 |
+----+----------------+----------------------------+---------------------+-------------------+----------------+---------------+---------------------+---------------------+--------+
7 rows in set (0.00 sec)


* Build & Run *NON-Quartz Scheduler* (backing on DB) and getting from NEXUS KJAR (change version of KJAR)

	mvn clean package spring-boot:run -Dspring.profiles.active=mysql-quartz -Dorg.kie.server.startup.strategy=LocalContainersStartupStrategy -Dorg.kie.server.mode=DEVELOPMENT -DSB_KIE_MODULE_GAV=com.redhat:payments:4.12.0 -Dkie.maven.settings.custom=/home/stkousso/.m2/hapoalim-settings.xml -s ~/.m2/hapoalim-settings.xml



* Build & Run *With Quartz Scheduler* (backing on DB) and getting from NEXUS KJAR (change version of KJAR)

	mvn clean package spring-boot:run -Dspring.profiles.active=mysql-quartz -Dorg.kie.server.startup.strategy=LocalContainersStartupStrategy -Dorg.kie.server.mode=DEVELOPMENT -DSB_KIE_MODULE_GAV=com.redhat:payments:4.12.0 -Dkie.maven.settings.custom=/home/stkousso/.m2/hapoalim-settings.xml -s ~/.m2/hapoalim-settings.xml


* Some errors (I believe due to MySQL not Quartz confiigs) appear but seem not to affect DB or Timer/Scheduler functionality

	java.sql.SQLException: Auto-commit can not be set while enrolled in a transaction
		at org.apache.commons.dbcp2.managed.ManagedConnection.setAutoCommit(ManagedConnection.java:253) ~[commons-dbcp2-2.5.0.jar!/:2.5.0]
		at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.setAutoCommit(AttributeRestoringConnectionInvocationHandler.java:98) ~[quartz-2.3.0.jar!/:na]
		at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:66) ~[quartz-2.3.0.jar!/:na]
		at com.sun.proxy.$Proxy166.setAutoCommit(Unknown Source) ~[na:na]



=== openshift profile

* See below for Openshift Setups

* Problem remains the SWAGGER/Classes scanning (all APIs corretly exposed but not scanned due to my own scanning)







==== OCP Resources Setup


* OCP Resources can be found at ./src/main/fabric8 
** link:./src/main/fabric8/mvn-cm.yml[mvn-cm.yml] OCP settings.xml to point to the correct Nexus/Artifactory mirror
** link:./src/main/fabric8/deployment.yml[deployment.yml] - Update (currently) the following with the application version details
*** change the version of the app: 

	image: image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.6.1

** link:./Dockerfile[Dockerfile] to utilize the correct version of the JAR to be added to the image

	COPY target/pam-rabbitmq-service-1.6.1.jar /deployments/

*** change the version of the KJAR: 

	            - name: SB_KIE_MODULE_GAV
              value: 'com.redhat:payments:4.7.0'

** link:./src/main/fabric8/kieserver-state-cm.yml[kieserver-state-cm.yml] - JBPM KJAR and controller configs. 
*** Update the KJAR Version when changing KJAR

** Create Secret  kie-api-credentials
oc create secret generic kie-api-credentials --from-literal=kie-api-svc-user=admin --from-literal=kie-api-svc-password='hapoalim!123'

** Create Secret rabbitmq-connection-details 
oc create secret generic rabbitmq-connection-details --from-literal=rabbitmq-host=rabbitmq --from-literal=rabbitmq-port=5672 --from-literal=rabbitmq-username=guest --from-literal=rabbitmq-password=guest

==== Fabric8 Docker Based binary build

* see pom.xml for Openshift Resources and method of build and change location of distributiob

    <distributionManagement>
        <repository>
            <id>releases</id>
            <!-- CHANGE HERE by your team nexus server -->
            <url>http://nexus-cicd-pam.apps.cluster-hapoalim-5d5c.hapoalim-5d5c.example.opentlc.com/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <id>snapshots</id>
            <!-- CHANGE HERE by your team nexus server -->
            <url>http://nexus-cicd-pam.apps.cluster-hapoalim-5d5c.hapoalim-5d5c.example.opentlc.com/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>


* Build & Apply Resources (both for some reason)

	mvn clean package fabric8:build fabric8:resource-apply -o -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dmaven.artifact.threads=50 -s /home/stkousso/.m2/hapoalim-settings.xml
	mvn fabric8:resource fabric8:resource-apply -o -P openshift -Dmaven.artifact.threads=50  -s /home/stkousso/.m2/hapoalim-settings.xml

** If not updating version of service version then also

        oc rollout latest dc/pam-rabbitmq-service -n rabbitmq








ARCHIVED COMMANDS
-------------------
1211  mvn clean package fabric8:build -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/amazon-buyjourney-service:1.0.3
 1214  mvn clean package fabric8:build -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/amazon-buyjourney-service:1.0.3
 1215  mvn fabric8:resource fabric8:resource-apply -Dfabric8.openshift.enableAutomaticTrigger=false -Dfabric8.openshift.imageChangeTrigger=false -Dfabric8.namespace=rabbitmq -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/amazon-buyjourney-service:1.0.3
 1217  mvn clean package fabric8:build -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.0
 1218  mvn fabric8:resource fabric8:resource-apply -Dfabric8.openshift.enableAutomaticTrigger=false -Dfabric8.openshift.imageChangeTrigger=false -Dfabric8.namespace=rabbitmq -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.0
 1219  mvn clean package fabric8:build -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.0
 1243  mvn clean package fabric8:build -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.1
 1246  mvn clean package fabric8:build -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.1
 1247  mvn fabric8:resource fabric8:resource-apply -Dfabric8.openshift.enableAutomaticTrigger=false -Dfabric8.openshift.imageChangeTrigger=false -Dfabric8.namespace=rabbitmq -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.1
 1249  mvn fabric8:resource fabric8:resource-apply 
 1250  ll src/main/fabric8/
 1251  vim src/main/fabric8/svc.yml 
 1257  vim main/fabric8/route.yml 
 1265  mvn fabric8:resource fabric8:resource-apply
 1266  mvn fabric8:resource-apply 
 1269  mvn clean package fabric8:build -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.2
 1272  mvn clean package fabric8:build -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.2
 1273  mvn clean package fabric8:build -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.3
 1274  mvn fabric8:resource-apply -p Openshift
 1275  mvn fabric8:resource-apply -P openshift
 1276  mvn fabric8:resource fabric8:resource-apply
 1278  vim src/main/fabric8/kieserver-state-cm.yml
 1279  mvn clean package fabric8:build -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.3
 1280  mvn fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50
 1281  mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50
 1282  vim src/main/fabric8/deployment.yml
 1283  mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50
 1286  vim src/main/fabric8/deployment.yml
 1287  mvn clean package fabric8:deploy -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.4 -Dmaven.artifact.threads=50
 1288  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.4 -Dmaven.artifact.threads=50
 1289  history |grep fabric8
 1290  mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.0.4
 1291  vim src/main/fabric8/kieserver-state-cm.yml
 1300  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.4 -Dmaven.artifact.threads=50
 1305  vim src/main/fabric8/deployment.yml
 1306  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.5 -Dmaven.artifact.threads=50
 1307  mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.0.5
 1308  vim src/main/fabric8/deployment.yml 
 1309  mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.0.5
 1312  vim src/main/fabric8/deployment.
 1313  vim src/main/fabric8/deployment.yml
 1314  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.6 -Dmaven.artifact.threads=50
 1315  mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.0.6
 1325  vim src/main/fabric8/deployment.yml
 1326  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.7 -Dmaven.artifact.threads=50
 1327  mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.0.6


  798  mvn clean fabric8:build -P openshift -Dmaven.artifact.threads=30
  799  mvn clean fabric8:deploy -P openshift -Dmaven.artifact.threads=30
  801  mvn clean fabric8:deploy -P openshift -Dmaven.artifact.threads=30 -Dregistry.username=redhat -Dregistry.password='redhat!1' -Ddocker.registry=image-registry.openshift-image-registry.svc:5000
  803  mvn clean fabric8:deploy -P openshift -Dmaven.artifact.threads=30 -Dregistry.username=skousou@gmail.com -Dregistry.password=404keratea2011 -Ddocker.registry=quay.io
 1035  vim src/main/fabric8/deployment.yml 
 1037  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.8 -Dmaven.artifact.threads=50
 1039   mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.0.8
 1044  vi src/main/fabric8/deployment.yml 
 1045  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.8 -Dmaven.artifact.threads=50
 1046   mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.0.8
 1054  vim src/main/fabric8/deployment.yml 
 1055  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.8 -Dmaven.artifact.threads=50
 1056  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.0.10 -Dmaven.artifact.threads=50
 1057   mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.0.10
 1062  vim src/main/fabric8/mvn-cm.yml 
 1109  gedit src/main/fabric8/kieserver-state-cm.yml &
 1118  vim src/main/fabric8/deployment.yml 
 1119  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.2.0 -Dmaven.artifact.threads=50
 1120   mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.2.0
 1132  vim src/main/fabric8/kieserver-state-cm.yml 
 1136  vim src/main/fabric8/deployment.yml 
 1137  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.2.0 -Dmaven.artifact.threads=50
 1138   mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.3.0
 1152  vim src/main/fabric8/kieserver-state-cm.yml
 1156  vim src/main/fabric8/deployment.yml 
 1157  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.2.0 -Dmaven.artifact.threads=50
 1158   mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.3.1
 1165  vim src/main/fabric8/deployment.yml 
 1167  mvn clean package fabric8:build fabric8:resource-apply -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.2.0 -Dmaven.artifact.threads=50 -s /home/stkousso/.m2/hapoel-settings.xml
 1168*  mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.3.3
 1169   mvn fabric8:resource fabric8:resource-apply -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.3.2 -s /home/stkousso/.m2/hapoel-settings.xml
 1171  mvn clean package fabric8:build fabric8:resource-apply -o -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.3.3 -Dmaven.artifact.threads=50 -s /home/stkousso/.m2/hapoel-settings.xml
 1173  vim src/main/fabric8/deployment.yml 
 1174  mvn clean package fabric8:build fabric8:resource-apply -o -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.3.3 -Dmaven.artifact.threads=50 -s /home/stkousso/.m2/hapoel-settings.xml
 1175  mvn clean package fabric8:build fabric8:resource-apply -o -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.3.3 -Dmaven.artifact.threads=50 -s /home/stkousso/.m2/hapoalim-settings.xml
 1176   mvn fabric8:resource fabric8:resource-apply -o -P openshift -Dmaven.artifact.threads=50 -Dfabric8.generator.name=image-registry.openshift-image-registry.svc:5000/rabbitmq/pam-rabbitmq-service:1.3.3 -s /home/stkousso/.m2/hapoalim-settings.xml


mvn clean package fabric8:build fabric8:resource-apply -o -Dfabric8.namespace=rabbitmq -DskipTests=true -P openshift -Dfabric8.generator.name=docker-registry.default.svc:5000/rabbtmq/pam-rabbitmq-service:1.3.3 -Dmaven.artifact.threads=50 -s /home/stkousso/.m2/hapoalim-settings.xml
