apiVersion: v1
data:
  pam-rabbitmq-service.xml: |-
    <kie-server-state>
      <!--controllers>
        <string>ws://myapp-rhpamcentrmon:8080/websocket/controller</string>
      </controllers-->
      <configuration>
        <configItems>
          <config-item>
            <name>org.kie.server.controller.user</name>
            <value>controllerUser</value>
            <type>java.lang.String</type>
          </config-item>
          <config-item>
            <name>org.kie.server.controller.pwd</name>
            <value>esgTfQ0!</value>
            <type>java.lang.String</type>
          </config-item>
          <config-item>
            <name>org.kie.server.user</name>
            <value>executionUser</value>
            <type>java.lang.String</type>
          </config-item>
          <config-item>
            <name>org.kie.server.pwd</name>
            <value>JsiVeq8!</value>
            <type>java.lang.String</type>
          </config-item>
          <!--config-item>
            <name>org.kie.server.controller</name>
            <value>ws://myapp-rhpamcentrmon:8080/websocket/controller</value>
            <type>java.lang.String</type>
          </config-item-->
          <config-item>
            <name>org.kie.server.id</name>
            <value>pam-rabbitmq-service</value>
            <type>java.lang.String</type>
          </config-item>
          <config-item>
            <name>org.kie.server.location</name>
            <value>http://pam-rabbitmq-service:8090/rest/server</value>
            <type>java.lang.String</type>
          </config-item>
        </configItems>
      </configuration>
      <containers>
        <!--container>
          <containerId>com.redhat:new-hire:2.0.0</containerId>
          <releaseId>
            <groupId>com.redhat</groupId>
            <artifactId>new-hire</artifactId>
            <version>2.0.0</version>
          </releaseId>
          <status>STARTED</status>
          <scanner>
            <status>STOPPED</status>
          </scanner>
          <configItems>
            <config-item>
              <name>KBase</name>
              <value></value>
              <type>BPM</type>
            </config-item>
            <config-item>
              <name>KSession</name>
              <value></value>
              <type>BPM</type>
            </config-item>
            <config-item>
              <name>MergeMode</name>
              <value>MERGE_COLLECTIONS</value>
              <type>BPM</type>
            </config-item>
            <config-item>
              <name>RuntimeStrategy</name>
              <value>PER_PROCESS_INSTANCE</value>
              <type>BPM</type>
            </config-item>
          </configItems>
          <messages/>
          <containerAlias>new-hire</containerAlias>
        </container-->
        <container>
          <containerId>com.redhat:payments:4.12.0</containerId>
          <releaseId>
            <groupId>com.redhat</groupId>
            <artifactId>payments</artifactId>
            <version>4.12.0</version>
          </releaseId>
          <status>STARTED</status>
          <scanner>
            <status>STOPPED</status>
          </scanner>
          <configItems>
            <config-item>
              <name>KBase</name>
              <value></value>
              <type>BPM</type>
            </config-item>
            <config-item>
              <name>KSession</name>
              <value></value>
              <type>BPM</type>
            </config-item>
            <config-item>
              <name>MergeMode</name>
              <value>MERGE_COLLECTIONS</value>
              <type>BPM</type>
            </config-item>
            <config-item>
              <name>RuntimeStrategy</name>
              <value>PER_PROCESS_INSTANCE</value>
              <type>BPM</type>
            </config-item>
          </configItems>
          <messages/>
          <containerAlias>payments</containerAlias>
        </container>
      </containers>
    </kie-server-state>
kind: ConfigMap
metadata:
  name: pam-rabbitmq-service-kie-server-state
