apiVersion: v1
data:
  settings.xml: |-
    <?xml version="1.0"?>
    <settings>
        <localRepository>/deployments/maven/repository</localRepository>
        <mirrors>
            <mirror>
                <id>central</id>
                <name>central</name>
                <!--url>http://nexus3-dsk-nexus.apps.na39.openshift.opentlc.com/repository/maven-all-public/</url-->
                <!--url>http://nexus3-GUID-nexus.svc.cluster.local:8081/repository/maven-all-public/</url-->
                <!--url>http://nexus3-tools.192.168.42.21.nip.io/repository/maven-all-public/</url-->
                <url>http://nexus-cicd-pam.apps.cluster-hapoalim-5d5c.hapoalim-5d5c.example.opentlc.com/repository/maven-all-public</url>
                <mirrorOf>*</mirrorOf>
            </mirror>
        </mirrors>
        <servers>
             <server>
                <id>releases</id>
                <username>admin</username>
                <password>admin123</password>
            </server>
            <server>
                <id>snapshots</id>
                <username>admin</username>
                <password>admin123</password>
            </server>
        </servers>
        <profiles>
            <!-- Configure the JBoss GA Maven repository -->
            <profile>
                <id>maven-all-public</id>
                <repositories>
                    <repository>
                        <id>maven-all-public</id>
                        <url>http://nexus-cicd-pam.apps.cluster-hapoalim-5d5c.hapoalim-5d5c.example.opentlc.com/repository/maven-all-public/</url>
                        <releases>
                            <enabled>true</enabled>
                        </releases>
                        <snapshots>
                            <enabled>true</enabled>
                        </snapshots>
                    </repository>
                    <repository>
                        <id>redhat-ga</id>
                        <name>Red Hat GA Repository</name>
                        <url>http://nexus-cicd-pam.apps.cluster-hapoalim-5d5c.hapoalim-5d5c.example.opentlc.com/repository/redhat-ga/</url>
                        <releases>
                            <enabled>true</enabled>
                        </releases>
                        <snapshots>
                            <enabled>true</enabled>
                        </snapshots>
                    </repository>
                </repositories>
                <pluginRepositories>
                    <pluginRepository>
                        <id>maven-all-public</id>
                        <url>http://nexus-cicd-pam.apps.cluster-hapoalim-5d5c.hapoalim-5d5c.example.opentlc.com/repository/maven-all-public/</url>
                        <releases>
                            <enabled>true</enabled>
                        </releases>
                        <snapshots>
                            <enabled>true</enabled>
                        </snapshots>
                    </pluginRepository>
                    <pluginRepository>
                        <id>redhat-ga</id>
                        <name>Red Hat GA Repository</name>
                        <url>http://nexus-cicd-pam.apps.cluster-hapoalim-5d5c.hapoalim-5d5c.example.opentlc.com/repository/redhat-ga/</url>
                        <releases>
                            <enabled>true</enabled>
                        </releases>
                        <snapshots>
                            <enabled>true</enabled>
                        </snapshots>
                    </pluginRepository>
                </pluginRepositories>
            </profile>
        </profiles>
        <activeProfiles>
            <!-- Optionally, make the repository active by default -->
            <activeProfile>maven-all-public</activeProfile>
        </activeProfiles>

    </settings>
kind: ConfigMap
metadata:
  name: mvn-settings
